export const ADD_ALBUM_REQUEST = "ADD_ALBUM_REQUEST";
export const ADD_ALBUM_SUCCESS = "ADD_ALBUM_SUCCESS";
export const ADD_ALBUM_FAILED = "ADD_ALBUM_FAILED";

export const DELETE_ALBUM_REQUEST = "DELETE_ALBUM_REQUEST";
export const DELETE_ALBUM_SUCCESS = "DELETE_ALBUM_SUCCESS";
export const DELETE_ALBUM_FAILED = "DELETE_ALBUM_FAILED";

export const FETCH_ALBUMS_REQUEST = "FETCH_ALBUMS_REQUEST";
export const FETCH_ALBUMS_SUCCESS = "FETCH_ALBUMS_SUCCESS";
export const FETCH_ALBUMS_FAILED = "FETCH_ALBUMS_FAILED";

export const FETCH_ALBUM_BY_ID_REQUEST = "FETCH_ALBUM_BY_ID_REQUEST";
export const FETCH_ALBUM_BY_ID_SUCCESS = "FETCH_ALBUM_BY_ID_SUCCESS";
export const FETCH_ALBUM_BY_ID_FAILED = "FETCH_ALBUM_BY_ID_FAILED";

export const FETCH_ALBUM_REQUEST = "FETCH_ALBUM_REQUEST";
export const FETCH_ALBUM_SUCCESS = "FETCH_ALBUM_SUCCESS";
export const FETCH_ALBUM_FAILED = "FETCH_ALBUM_FAILED";

export const UPDATE_ALBUM_REQUEST = "UPDATE_ALBUM_REQUEST";
export const UPDATE_ALBUM_SUCCESS = "UPDATE_ALBUM_SUCCESS";
export const UPDATE_ALBUM_FAILED = "UPDATE_ALBUM_FAILED";

export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILED = "FETCH_SEARCH_FAILED";

export const TOGGLE_IS_SONG_SELECTED = "TOGGLE_IS_SONG_SELECTED";
export const STORE_SELECTED_ALBUM = "STORE_SELECTED_ALBUM";
export const TOGGLE_IS_ALBUM_SELECTED = "TOGGLE_IS_ALBUM_SELECTED";

export const SHOW_SEARCH_RESULT = "SHOW_SEARCH_RESULT";
export const HIDE_SEARCH_RESULT = "HIDE_SEARCH_RESULT";
