export const FETCH_ARTIST_BY_ID_REQUEST = 'FETCH_ARTIST_BY_ID_REQUEST';
export const FETCH_ARTIST_BY_ID_SUCCESS = 'FETCH_ARTIST_BY_ID_SUCCESS';
export const FETCH_ARTIST_BY_ID_FAILED = 'FETCH_ARTIST_BY_ID_FAILED';

export const FETCH_ARTISTS_REQUEST = 'FETCH_ARTISTS_REQUEST';
export const FETCH_ARTISTS_SUCCESS = 'FETCH_ARTISTS_SUCCESS';
export const FETCH_ARTISTS_FAILED = 'FETCH_ARTISTS_FAILED';

// export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST';
// export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
// export const FETCH_ARTIST_FAILED = 'FETCH_ARTIST_FAILED';
