
export const ADD_FOLLOWER_REQUEST = 'ADD_FOLLOWER_REQUEST';
export const ADD_FOLLOWER_SUCCESS = 'ADD_FOLLOWER_SUCCESS';
export const ADD_FOLLOWER_FAILED = 'ADD_FOLLOWER_FAILED';

export const DELETE_FOLLOWER_REQUEST = 'DELETE_FOLLOWER_REQUEST';
export const DELETE_FOLLOWER_SUCCESS = 'DELETE_FOLLOWER_SUCCESS';
export const DELETE_FOLLOWER_FAILED = 'DELETE_FOLLOWER_FAILED';

export const FETCH_FOLLOWERS_REQUEST = 'FETCH_FOLLOWERS_REQUEST';
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';
export const FETCH_FOLLOWERS_FAILED = 'FETCH_FOLLOWERS_FAILED';

export const FETCH_FOLLOWER_BY_ID_REQUEST = 'FETCH_FOLLOWER_BY_ID_REQUEST';
export const FETCH_FOLLOWER_BY_ID_SUCCESS = 'FETCH_FOLLOWER_BY_ID_SUCCESS';
export const FETCH_FOLLOWER_BY_ID_FAILED = 'FETCH_FOLLOWER_BY_ID_FAILED';

export const FETCH_FOLLOWER_REQUEST = 'FETCH_FOLLOWER_REQUEST';
export const FETCH_FOLLOWER_SUCCESS = 'FETCH_FOLLOWER_SUCCESS';
export const FETCH_FOLLOWER_FAILED = 'FETCH_FOLLOWER_FAILED';

export const UPDATE_FOLLOWER_REQUEST = 'UPDATE_FOLLOWER_REQUEST';
export const UPDATE_FOLLOWER_SUCCESS = 'UPDATE_FOLLOWER_SUCCESS';
export const UPDATE_FOLLOWER_FAILED = 'UPDATE_FOLLOWER_FAILED';
