export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_OVERLAY_LOADER = 'SET_OVERLAY_LOADER';
export const UNSET_OVERLAY_LOADER = 'UNSET_OVERLAY_LOADER';
export const SET_IS_ERROR_PAGE = 'SET_IS_ERROR_PAGE';
export const UNSET_IS_ERROR_PAGE = 'UNSET_IS_ERROR_PAGE';
export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU';
export const SHOW_PURCHASE_MODAL = 'SHOW_PURCHASE_MODAL';
export const HIDE_PURCHASE_MODAL = 'HIDE_PURCHASE_MODAL';
