
export const ADD_MARKETPLACESONG_REQUEST = 'ADD_MARKETPLACESONG_REQUEST';
export const ADD_MARKETPLACESONG_SUCCESS = 'ADD_MARKETPLACESONG_SUCCESS';
export const ADD_MARKETPLACESONG_FAILED = 'ADD_MARKETPLACESONG_FAILED';

export const DELETE_MARKETPLACESONG_REQUEST = 'DELETE_MARKETPLACESONG_REQUEST';
export const DELETE_MARKETPLACESONG_SUCCESS = 'DELETE_MARKETPLACESONG_SUCCESS';
export const DELETE_MARKETPLACESONG_FAILED = 'DELETE_MARKETPLACESONG_FAILED';

export const FETCH_MARKETPLACESONGS_REQUEST = 'FETCH_MARKETPLACESONGS_REQUEST';
export const FETCH_MARKETPLACESONGS_SUCCESS = 'FETCH_MARKETPLACESONGS_SUCCESS';
export const FETCH_MARKETPLACESONGS_FAILED = 'FETCH_MARKETPLACESONGS_FAILED';

export const FETCH_MARKETPLACESONG_BY_ID_REQUEST = 'FETCH_MARKETPLACESONG_BY_ID_REQUEST';
export const FETCH_MARKETPLACESONG_BY_ID_SUCCESS = 'FETCH_MARKETPLACESONG_BY_ID_SUCCESS';
export const FETCH_MARKETPLACESONG_BY_ID_FAILED = 'FETCH_MARKETPLACESONG_BY_ID_FAILED';

export const FETCH_MARKETPLACESONG_REQUEST = 'FETCH_MARKETPLACESONG_REQUEST';
export const FETCH_MARKETPLACESONG_SUCCESS = 'FETCH_MARKETPLACESONG_SUCCESS';
export const FETCH_MARKETPLACESONG_FAILED = 'FETCH_MARKETPLACESONG_FAILED';

export const UPDATE_MARKETPLACESONG_REQUEST = 'UPDATE_MARKETPLACESONG_REQUEST';
export const UPDATE_MARKETPLACESONG_SUCCESS = 'UPDATE_MARKETPLACESONG_SUCCESS';
export const UPDATE_MARKETPLACESONG_FAILED = 'UPDATE_MARKETPLACESONG_FAILED';
