
export const ADD_NFT_REQUEST = 'ADD_NFT_REQUEST';
export const ADD_NFT_SUCCESS = 'ADD_NFT_SUCCESS';
export const ADD_NFT_FAILED = 'ADD_NFT_FAILED';

export const DELETE_NFT_REQUEST = 'DELETE_NFT_REQUEST';
export const DELETE_NFT_SUCCESS = 'DELETE_NFT_SUCCESS';
export const DELETE_NFT_FAILED = 'DELETE_NFT_FAILED';

export const FETCH_NFTS_REQUEST = 'FETCH_NFTS_REQUEST';
export const FETCH_NFTS_SUCCESS = 'FETCH_NFTS_SUCCESS';
export const FETCH_NFTS_FAILED = 'FETCH_NFTS_FAILED';

export const FETCH_NFT_BY_ID_REQUEST = 'FETCH_NFT_BY_ID_REQUEST';
export const FETCH_NFT_BY_ID_SUCCESS = 'FETCH_NFT_BY_ID_SUCCESS';
export const FETCH_NFT_BY_ID_FAILED = 'FETCH_NFT_BY_ID_FAILED';

export const FETCH_NFT_REQUEST = 'FETCH_NFT_REQUEST';
export const FETCH_NFT_SUCCESS = 'FETCH_NFT_SUCCESS';
export const FETCH_NFT_FAILED = 'FETCH_NFT_FAILED';

export const UPDATE_NFT_REQUEST = 'UPDATE_NFT_REQUEST';
export const UPDATE_NFT_SUCCESS = 'UPDATE_NFT_SUCCESS';
export const UPDATE_NFT_FAILED = 'UPDATE_NFT_FAILED';

export const MINT_NFT_REQUEST = 'MINT_NFT_REQUEST';
export const MINT_NFT_SUCCESS = 'MINT_NFT_SUCCESS';
export const MINT_NFT_FAILED = 'MINT_NFT_FAILED';

export const BUY_ALBUM_BUNDLE_NFT_REQUEST = 'BUY_ALBUM_BUNDLE_NFT_REQUEST';
export const BUY_ALBUM_BUNDLE_NFT_SUCCESS = 'BUY_ALBUM_BUNDLE_NFT_SUCCESS';
export const BUY_ALBUM_BUNDLE_NFT_FAILED = 'BUY_ALBUM_BUNDLE_NFT_FAILED';

export const SELL_SONG_NFT_REQUEST = 'SELL_SONG_NFT_REQUEST';
export const SELL_SONG_NFT_SUCCESS = 'SELL_SONG_NFT_SUCCESS';
export const SELL_SONG_NFT_FAILED = 'SELL_SONG_NFT_FAILED';

export const BUY_SONG_NFT_REQUEST = 'BUY_SONG_NFT_REQUEST';
export const BUY_SONG_NFT_SUCCESS = 'BUY_SONG_NFT_SUCCESS';
export const BUY_SONG_NFT_FAILED = 'BUY_SONG_NFT_FAILED';

export const UPDATE_SEND_MONEY_REQUEST = 'UPDATE_SEND_MONEY_REQUEST';
export const UPDATE_SEND_MONEY_SUCCESS = 'UPDATE_SEND_MONEY_SUCCESS';
export const UPDATE_SEND_MONEY_FAILED = 'UPDATE_SEND_MONEY_FAILED';
