
export const ADD_NOMINATIONVOTE_REQUEST = 'ADD_NOMINATIONVOTE_REQUEST';
export const ADD_NOMINATIONVOTE_SUCCESS = 'ADD_NOMINATIONVOTE_SUCCESS';
export const ADD_NOMINATIONVOTE_FAILED = 'ADD_NOMINATIONVOTE_FAILED';

export const DELETE_NOMINATIONVOTE_REQUEST = 'DELETE_NOMINATIONVOTE_REQUEST';
export const DELETE_NOMINATIONVOTE_SUCCESS = 'DELETE_NOMINATIONVOTE_SUCCESS';
export const DELETE_NOMINATIONVOTE_FAILED = 'DELETE_NOMINATIONVOTE_FAILED';

export const FETCH_NOMINATIONVOTES_REQUEST = 'FETCH_NOMINATIONVOTES_REQUEST';
export const FETCH_NOMINATIONVOTES_SUCCESS = 'FETCH_NOMINATIONVOTES_SUCCESS';
export const FETCH_NOMINATIONVOTES_FAILED = 'FETCH_NOMINATIONVOTES_FAILED';

export const FETCH_NOMINATIONVOTE_BY_ID_REQUEST = 'FETCH_NOMINATIONVOTE_BY_ID_REQUEST';
export const FETCH_NOMINATIONVOTE_BY_ID_SUCCESS = 'FETCH_NOMINATIONVOTE_BY_ID_SUCCESS';
export const FETCH_NOMINATIONVOTE_BY_ID_FAILED = 'FETCH_NOMINATIONVOTE_BY_ID_FAILED';

export const FETCH_NOMINATIONVOTE_REQUEST = 'FETCH_NOMINATIONVOTE_REQUEST';
export const FETCH_NOMINATIONVOTE_SUCCESS = 'FETCH_NOMINATIONVOTE_SUCCESS';
export const FETCH_NOMINATIONVOTE_FAILED = 'FETCH_NOMINATIONVOTE_FAILED';

export const UPDATE_NOMINATIONVOTE_REQUEST = 'UPDATE_NOMINATIONVOTE_REQUEST';
export const UPDATE_NOMINATIONVOTE_SUCCESS = 'UPDATE_NOMINATIONVOTE_SUCCESS';
export const UPDATE_NOMINATIONVOTE_FAILED = 'UPDATE_NOMINATIONVOTE_FAILED';
