export const ADD_NOMINATION_REQUEST = "ADD_NOMINATION_REQUEST";
export const ADD_NOMINATION_SUCCESS = "ADD_NOMINATION_SUCCESS";
export const ADD_NOMINATION_FAILED = "ADD_NOMINATION_FAILED";

export const DELETE_NOMINATION_REQUEST = "DELETE_NOMINATION_REQUEST";
export const DELETE_NOMINATION_SUCCESS = "DELETE_NOMINATION_SUCCESS";
export const DELETE_NOMINATION_FAILED = "DELETE_NOMINATION_FAILED";

export const FETCH_NOMINATIONS_REQUEST = "FETCH_NOMINATIONS_REQUEST";
export const FETCH_NOMINATIONS_SUCCESS = "FETCH_NOMINATIONS_SUCCESS";
export const FETCH_NOMINATIONS_FAILED = "FETCH_NOMINATIONS_FAILED";

export const FETCH_NOMINATION_BY_ID_REQUEST = "FETCH_NOMINATION_BY_ID_REQUEST";
export const FETCH_NOMINATION_BY_ID_SUCCESS = "FETCH_NOMINATION_BY_ID_SUCCESS";
export const FETCH_NOMINATION_BY_ID_FAILED = "FETCH_NOMINATION_BY_ID_FAILED";

export const FETCH_NOMINATION_REQUEST = "FETCH_NOMINATION_REQUEST";
export const FETCH_NOMINATION_SUCCESS = "FETCH_NOMINATION_SUCCESS";
export const FETCH_NOMINATION_FAILED = "FETCH_NOMINATION_FAILED";

export const UPDATE_NOMINATION_REQUEST = "UPDATE_NOMINATION_REQUEST";
export const UPDATE_NOMINATION_SUCCESS = "UPDATE_NOMINATION_SUCCESS";
export const UPDATE_NOMINATION_FAILED = "UPDATE_NOMINATION_FAILED";

export const TOGGLE_NOMINATE_CONGRATS_MODAL = "TOGGLE_NOMINATE_CONGRATS_MODAL";
export const TOGGLE_NOMINATE = "TOGGLE_NOMINATE";

export const ADD_NOMINATION_VOTE = "ADD_NOMINATION_VOTE";
