
export const ADD_PLAYLIST_REQUEST = 'ADD_PLAYLIST_REQUEST';
export const ADD_PLAYLIST_SUCCESS = 'ADD_PLAYLIST_SUCCESS';
export const ADD_PLAYLIST_FAILED = 'ADD_PLAYLIST_FAILED';

export const DELETE_PLAYLIST_REQUEST = 'DELETE_PLAYLIST_REQUEST';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAILED = 'DELETE_PLAYLIST_FAILED';

export const FETCH_PLAYLISTS_REQUEST = 'FETCH_PLAYLISTS_REQUEST';
export const FETCH_PLAYLISTS_SUCCESS = 'FETCH_PLAYLISTS_SUCCESS';
export const FETCH_PLAYLISTS_FAILED = 'FETCH_PLAYLISTS_FAILED';

export const FETCH_PLAYLIST_BY_ID_REQUEST = 'FETCH_PLAYLIST_BY_ID_REQUEST';
export const FETCH_PLAYLIST_BY_ID_SUCCESS = 'FETCH_PLAYLIST_BY_ID_SUCCESS';
export const FETCH_PLAYLIST_BY_ID_FAILED = 'FETCH_PLAYLIST_BY_ID_FAILED';

export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST';
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS';
export const FETCH_PLAYLIST_FAILED = 'FETCH_PLAYLIST_FAILED';

export const UPDATE_PLAYLIST_REQUEST = 'UPDATE_PLAYLIST_REQUEST';
export const UPDATE_PLAYLIST_SUCCESS = 'UPDATE_PLAYLIST_SUCCESS';
export const UPDATE_PLAYLIST_FAILED = 'UPDATE_PLAYLIST_FAILED';

export const UPDATE_CURRENT_PLAYLIST_REQUEST = 'UPDATE_CURRENT_PLAYLIST_REQUEST';

export const CLEAR_CURRENTPLAYLIST_REQUEST = 'CLEAR_CURRENTPLAYLIST_REQUEST';

export const SHOW_PLAYLIST_DELETE_MODAL = 'SHOW_PLAYLIST_DELETE_MODAL';
export const HIDE_PLAYLIST_DELETE_MODAL = 'HIDE_PLAYLIST_DELETE_MODAL';

export const SHOW_PLAYLIST_MODAL = 'SHOW_PLAYLIST_MODAL';
export const HIDE_PLAYLIST_MODAL = 'HIDE_PLAYLIST_MODAL';
