
export const ADD_SHOWCASE_REQUEST = 'ADD_SHOWCASE_REQUEST';
export const ADD_SHOWCASE_SUCCESS = 'ADD_SHOWCASE_SUCCESS';
export const ADD_SHOWCASE_FAILED = 'ADD_SHOWCASE_FAILED';

export const DELETE_SHOWCASE_REQUEST = 'DELETE_SHOWCASE_REQUEST';
export const DELETE_SHOWCASE_SUCCESS = 'DELETE_SHOWCASE_SUCCESS';
export const DELETE_SHOWCASE_FAILED = 'DELETE_SHOWCASE_FAILED';

export const FETCH_SHOWCASES_REQUEST = 'FETCH_SHOWCASES_REQUEST';
export const FETCH_SHOWCASES_SUCCESS = 'FETCH_SHOWCASES_SUCCESS';
export const FETCH_SHOWCASES_FAILED = 'FETCH_SHOWCASES_FAILED';

export const FETCH_SHOWCASE_BY_ID_REQUEST = 'FETCH_SHOWCASE_BY_ID_REQUEST';
export const FETCH_SHOWCASE_BY_ID_SUCCESS = 'FETCH_SHOWCASE_BY_ID_SUCCESS';
export const FETCH_SHOWCASE_BY_ID_FAILED = 'FETCH_SHOWCASE_BY_ID_FAILED';

export const FETCH_SHOWCASE_REQUEST = 'FETCH_SHOWCASE_REQUEST';
export const FETCH_SHOWCASE_SUCCESS = 'FETCH_SHOWCASE_SUCCESS';
export const FETCH_SHOWCASE_FAILED = 'FETCH_SHOWCASE_FAILED';

export const UPDATE_SHOWCASE_REQUEST = 'UPDATE_SHOWCASE_REQUEST';
export const UPDATE_SHOWCASE_SUCCESS = 'UPDATE_SHOWCASE_SUCCESS';
export const UPDATE_SHOWCASE_FAILED = 'UPDATE_SHOWCASE_FAILED';
