
export const ADD_SONG_REQUEST = 'ADD_SONG_REQUEST';
export const ADD_SONG_SUCCESS = 'ADD_SONG_SUCCESS';
export const ADD_SONG_FAILED = 'ADD_SONG_FAILED';

export const DELETE_SONG_REQUEST = 'DELETE_SONG_REQUEST';
export const DELETE_SONG_SUCCESS = 'DELETE_SONG_SUCCESS';
export const DELETE_SONG_FAILED = 'DELETE_SONG_FAILED';

export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export const FETCH_SONGS_FAILED = 'FETCH_SONGS_FAILED';

export const FETCH_SONG_BY_ID_REQUEST = 'FETCH_SONG_BY_ID_REQUEST';
export const FETCH_SONG_BY_ID_SUCCESS = 'FETCH_SONG_BY_ID_SUCCESS';
export const FETCH_SONG_BY_ID_FAILED = 'FETCH_SONG_BY_ID_FAILED';

export const FETCH_SONG_REQUEST = 'FETCH_SONG_REQUEST';
export const FETCH_SONG_SUCCESS = 'FETCH_SONG_SUCCESS';
export const FETCH_SONG_FAILED = 'FETCH_SONG_FAILED';

export const UPDATE_SONG_REQUEST = 'UPDATE_SONG_REQUEST';
export const UPDATE_SONG_SUCCESS = 'UPDATE_SONG_SUCCESS';
export const UPDATE_SONG_FAILED = 'UPDATE_SONG_FAILED';

export const BUY_SONG_REQUEST = 'BUY_SONG_REQUEST';
export const BUY_SONG_SUCCESS = 'BUY_SONG_SUCCESS';
export const BUY_SONG_FAILED = 'BUY_SONG_FAILED';

export const SELL_SONG_REQUEST = 'SELL_SONG_REQUEST';
export const SELL_SONG_SUCCESS = 'SELL_SONG_SUCCESS';
export const SELL_SONG_FAILED = 'SELL_SONG_FAILED';

export const SELL_SONG_CONFIRMATION = 'SELL_SONG_CONFIRMATION';

export const HIDE_BUY_MODAL = 'HIDE_BUY_MODAL';
export const SHOW_BUY_MODAL = 'SHOW_BUY_MODAL';

export const HIDE_SELL_MODAL = 'HIDE_SELL_MODAL';
export const SHOW_SELL_MODAL = 'SHOW_SELL_MODAL';
