
export const ADD_SUPPORTER_PAYOUT_LOG_REQUEST = 'ADD_SUPPORTER_PAYOUT_LOG_REQUEST';
export const ADD_SUPPORTER_PAYOUT_LOG_SUCCESS = 'ADD_SUPPORTER_PAYOUT_LOG_SUCCESS';
export const ADD_SUPPORTER_PAYOUT_LOG_FAILED = 'ADD_SUPPORTER_PAYOUT_LOG_FAILED';

export const DELETE_SUPPORTER_PAYOUT_LOG_REQUEST = 'DELETE_SUPPORTER_PAYOUT_LOG_REQUEST';
export const DELETE_SUPPORTER_PAYOUT_LOG_SUCCESS = 'DELETE_SUPPORTER_PAYOUT_LOG_SUCCESS';
export const DELETE_SUPPORTER_PAYOUT_LOG_FAILED = 'DELETE_SUPPORTER_PAYOUT_LOG_FAILED';

export const FETCH_SUPPORTER_PAYOUT_LOGS_REQUEST = 'FETCH_SUPPORTER_PAYOUT_LOGS_REQUEST';
export const FETCH_SUPPORTER_PAYOUT_LOGS_SUCCESS = 'FETCH_SUPPORTER_PAYOUT_LOGS_SUCCESS';
export const FETCH_SUPPORTER_PAYOUT_LOGS_FAILED = 'FETCH_SUPPORTER_PAYOUT_LOGS_FAILED';

export const FETCH_SUPPORTER_PAYOUT_LOG_BY_ID_REQUEST = 'FETCH_SUPPORTER_PAYOUT_LOG_BY_ID_REQUEST';
export const FETCH_SUPPORTER_PAYOUT_LOG_BY_ID_SUCCESS = 'FETCH_SUPPORTER_PAYOUT_LOG_BY_ID_SUCCESS';
export const FETCH_SUPPORTER_PAYOUT_LOG_BY_ID_FAILED = 'FETCH_SUPPORTER_PAYOUT_LOG_BY_ID_FAILED';

export const FETCH_SUPPORTER_PAYOUT_LOG_REQUEST = 'FETCH_SUPPORTER_PAYOUT_LOG_REQUEST';
export const FETCH_SUPPORTER_PAYOUT_LOG_SUCCESS = 'FETCH_SUPPORTER_PAYOUT_LOG_SUCCESS';
export const FETCH_SUPPORTER_PAYOUT_LOG_FAILED = 'FETCH_SUPPORTER_PAYOUT_LOG_FAILED';

export const UPDATE_SUPPORTER_PAYOUT_LOG_REQUEST = 'UPDATE_SUPPORTER_PAYOUT_LOG_REQUEST';
export const UPDATE_SUPPORTER_PAYOUT_LOG_SUCCESS = 'UPDATE_SUPPORTER_PAYOUT_LOG_SUCCESS';
export const UPDATE_SUPPORTER_PAYOUT_LOG_FAILED = 'UPDATE_SUPPORTER_PAYOUT_LOG_FAILED';
