
export const ADD_TOKENTRANSFER_REQUEST = 'ADD_TOKENTRANSFER_REQUEST';
export const ADD_TOKENTRANSFER_SUCCESS = 'ADD_TOKENTRANSFER_SUCCESS';
export const ADD_TOKENTRANSFER_FAILED = 'ADD_TOKENTRANSFER_FAILED';

export const DELETE_TOKENTRANSFER_REQUEST = 'DELETE_TOKENTRANSFER_REQUEST';
export const DELETE_TOKENTRANSFER_SUCCESS = 'DELETE_TOKENTRANSFER_SUCCESS';
export const DELETE_TOKENTRANSFER_FAILED = 'DELETE_TOKENTRANSFER_FAILED';

export const FETCH_TOKENTRANSFERS_REQUEST = 'FETCH_TOKENTRANSFERS_REQUEST';
export const FETCH_TOKENTRANSFERS_SUCCESS = 'FETCH_TOKENTRANSFERS_SUCCESS';
export const FETCH_TOKENTRANSFERS_FAILED = 'FETCH_TOKENTRANSFERS_FAILED';

export const FETCH_TOKENTRANSFER_BY_ID_REQUEST = 'FETCH_TOKENTRANSFER_BY_ID_REQUEST';
export const FETCH_TOKENTRANSFER_BY_ID_SUCCESS = 'FETCH_TOKENTRANSFER_BY_ID_SUCCESS';
export const FETCH_TOKENTRANSFER_BY_ID_FAILED = 'FETCH_TOKENTRANSFER_BY_ID_FAILED';

export const FETCH_TOKENTRANSFER_REQUEST = 'FETCH_TOKENTRANSFER_REQUEST';
export const FETCH_TOKENTRANSFER_SUCCESS = 'FETCH_TOKENTRANSFER_SUCCESS';
export const FETCH_TOKENTRANSFER_FAILED = 'FETCH_TOKENTRANSFER_FAILED';

export const UPDATE_TOKENTRANSFER_REQUEST = 'UPDATE_TOKENTRANSFER_REQUEST';
export const UPDATE_TOKENTRANSFER_SUCCESS = 'UPDATE_TOKENTRANSFER_SUCCESS';
export const UPDATE_TOKENTRANSFER_FAILED = 'UPDATE_TOKENTRANSFER_FAILED';
